In [1]:
import kagglehub
import os
path = kagglehub.dataset_download("prevek18/ames-housing-dataset")
print(path)

Downloading to /root/.cache/kagglehub/datasets/prevek18/ames-housing-dataset/1.archive...

100%|██████████| 185k/185k [00:00<00:00, 68.4MB/s]

Extracting files...
/root/.cache/kagglehub/datasets/prevek18/ames-housing-dataset/versions/1

In [ ]:
import pandas as pd
print(os.listdir(path))
file_path = os.path.join(path, "AmesHousing.csv")
df = pd.read_csv(file_path)
df

['AmesHousing.csv']

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,923275080,80,RL,37.0,7937,Pave,NaN,IR1,Lvl,...,0,NaN,GdPrv,NaN,0,3,2006,WD,Normal,142500
2926,2927,923276100,20,RL,NaN,8885,Pave,NaN,IR1,Low,...,0,NaN,MnPrv,NaN,0,6,2006,WD,Normal,131000
2927,2928,923400125,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal,132000
2928,2929,924100070,20,RL,77.0,10010,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2006,WD,Normal,170000
2929,2930,924151050,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,11,2006,WD,Normal,188000

In [ ]:
df.shape

(2930, 82)

In [ ]:
df.describe()

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,...,93.751877,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,...,126.361562,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [ ]:
df.shape

(2930, 82)

In [ ]:
print(X.columns.tolist())

['Order', 'PID', 'MS SubClass', 'MS Zoning', 'Lot Frontage', 'Lot Area', 'Street', 'Alley', 'Lot Shape', 'Land Contour', 'Utilities', 'Lot Config', 'Land Slope', 'Neighborhood', 'Condition 1', 'Condition 2', 'Bldg Type', 'House Style', 'Overall Qual', 'Overall Cond', 'Year Built', 'Year Remod/Add', 'Roof Style', 'Roof Matl', 'Exterior 1st', 'Exterior 2nd', 'Mas Vnr Type', 'Mas Vnr Area', 'Exter Qual', 'Exter Cond', 'Foundation', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 'BsmtFin Type 1', 'BsmtFin SF 1', 'BsmtFin Type 2', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Total Bsmt SF', 'Heating', 'Heating QC', 'Central Air', 'Electrical', '1st Flr SF', '2nd Flr SF', 'Low Qual Fin SF', 'Gr Liv Area', 'Bsmt Full Bath', 'Bsmt Half Bath', 'Full Bath', 'Half Bath', 'Bedroom AbvGr', 'Kitchen AbvGr', 'Kitchen Qual', 'TotRms AbvGrd', 'Functional', 'Fireplaces', 'Fireplace Qu', 'Garage Type', 'Garage Yr Blt', 'Garage Finish', 'Garage Cars', 'Garage Area', 'Garage Qual', 'Garage Cond', 'Paved Drive', 'Wood Deck SF', 'Open Porch SF', 'Enclosed Porch', '3Ssn Porch', 'Screen Porch', 'Pool Area', 'Pool QC', 'Fence', 'Misc Feature', 'Misc Val', 'Mo Sold', 'Yr Sold', 'Sale Type', 'Sale Condition']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS SubClass      2930 non-null   int64
 3   MS Zoning        2930 non-null   object
 4   Lot Frontage     2440 non-null   float64
 5   Lot Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot Shape        2930 non-null   object
 9   Land Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot Config       2930 non-null   object
 12  Land Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition 1      2930 non-null   object
 15  Condition 2      2930 non-null   object
 16  Bldg Type        2930 non-null   object
 17  House Style      2930 non-null   object
 18  Overall Qual     2930 non-null   int64
 19  Overall Cond     2930 non-null   int64
 20  Year Built       2930 non-null   int64
 21  Year Remod/Add   2930 non-null   int64
 22  Roof Style       2930 non-null   object
 23  Roof Matl        2930 non-null   object
 24  Exterior 1st     2930 non-null   object
 25  Exterior 2nd     2930 non-null   object
 26  Mas Vnr Type     1155 non-null   object
 27  Mas Vnr Area     2907 non-null   float64
 28  Exter Qual       2930 non-null   object
 29  Exter Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt Qual        2850 non-null   object
 32  Bsmt Cond        2850 non-null   object
 33  Bsmt Exposure    2847 non-null   object
 34  BsmtFin Type 1   2850 non-null   object
 35  BsmtFin SF 1     2929 non-null   float64
 36  BsmtFin Type 2   2849 non-null   object
 37  BsmtFin SF 2     2929 non-null   float64
 38  Bsmt Unf SF      2929 non-null   float64
 39  Total Bsmt SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating QC       2930 non-null   object
 42  Central Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st Flr SF       2930 non-null   int64
 45  2nd Flr SF       2930 non-null   int64
 46  Low Qual Fin SF  2930 non-null   int64
 47  Gr Liv Area      2930 non-null   int64
 48  Bsmt Full Bath   2928 non-null   float64
 49  Bsmt Half Bath   2928 non-null   float64
 50  Full Bath        2930 non-null   int64
 51  Half Bath        2930 non-null   int64
 52  Bedroom AbvGr    2930 non-null   int64
 53  Kitchen AbvGr    2930 non-null   int64
 54  Kitchen Qual     2930 non-null   object
 55  TotRms AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace Qu     1508 non-null   object
 59  Garage Type      2773 non-null   object
 60  Garage Yr Blt    2771 non-null   float64
 61  Garage Finish    2771 non-null   object
 62  Garage Cars      2929 non-null   float64
 63  Garage Area      2929 non-null   float64
 64  Garage Qual      2771 non-null   object
 65  Garage Cond      2771 non-null   object
 66  Paved Drive      2930 non-null   object
 67  Wood Deck SF     2930 non-null   int64
 68  Open Porch SF    2930 non-null   int64
 69  Enclosed Porch   2930 non-null   int64
 70  3Ssn Porch       2930 non-null   int64
 71  Screen Porch     2930 non-null   int64
 72  Pool Area        2930 non-null   int64
 73  Pool QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc Feature     106 non-null    object
 76  Misc Val         2930 non-null   int64
 77  Mo Sold          2930 non-null   int64
 78  Yr Sold          2930 non-null   int64
 79  Sale Type        2930 non-null   object
 80  Sale Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [ ]:
df.shape

(2930, 82)

NULL VALUES HANDLING

In [ ]:
df.isnull().sum()

Order               0
PID                 0
MS SubClass         0
MS Zoning           0
Lot Frontage      490
                 ...
Mo Sold             0
Yr Sold             0
Sale Type           0
Sale Condition      0
SalePrice           0
Length: 82, dtype: int64

DUPLICATE VALUE HANDLING

In [ ]:
df[df.duplicated()].shape

(0, 82)

ENCODING

In [ ]:
X = df.iloc[:, 0:81]
Y = df.iloc[:, -1]

In [ ]:
print(df.shape)
print(X.shape)
print(Y.shape)

(2930, 82)
(2930, 81)
(2930,)

In [ ]:
cat_cols = X.select_dtypes(include='object').columns
num_cols = X.select_dtypes(exclude='object').columns

In [ ]:
from sklearn.compose import ColumnTransformer ## different preprocessing for differnt columns like - categorical or numerical
from sklearn.preprocessing import OneHotEncoder, StandardScaler ## OneHotEncoder for categorical , and StandardScaler for numerical
from sklearn.impute import SimpleImputer ## handle nan values
from sklearn.pipeline import Pipeline

num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')), ## first convert nan value to median
    ('scaler', StandardScaler())  ## then scale all the values
])

cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')), ## first convert nan to most frequent data
    ('onehot', OneHotEncoder(handle_unknown='ignore')) ##
])

In [ ]:
preprocessor = ColumnTransformer( ## now these pipeline is apply on the columns
    transformers=[
        ('num', num_pipeline, num_cols),
        ('cat', cat_pipeline, cat_cols)
    ]
)

TRAIN TEST SPLIT

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [ ]:
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

STANDARIZING

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler(with_mean=False)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

TRAIN MODEL

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

PREDICTION

In [ ]:
X_test_predict=model.predict(X_test)
X_train_predict=model.predict(X_train)

In [ ]:
X_test_predict

array([155885.41981272, 110068.89967812, 200065.7490722 , 129529.49661065,
       130589.12670052, 191984.02715336, 169757.39095576, 145721.08489631,
        98049.53407452, 365028.97786527, 223500.84687669, 251029.49008614,
        67199.08740867, 128911.81724627,  58936.37849502, 180620.57811983,
       138545.54477027, 193112.21186676, 129231.61818752, 154278.17145327,
       174479.88000404, 141351.31478445, 202391.47611078, 202689.78842268,
       196334.29724459, 262969.86078265, 370903.03188191, 229243.15938137,
       193952.58347689, 241204.07675487, 191118.26710037,  75059.29395679,
       212214.69468541,  84889.13821127, 118242.83637325,  66412.57782133,
       191339.78704689, 327546.32174409, 184300.08186839, 295070.0584779 ,
       343041.5035516 , 235385.88741182, 250470.16896307, 190028.1600563 ,
       133220.99133934, 328172.88880453, 185811.94116771, 155066.66034289,
       170549.47917049, 118463.18397627, 179020.17539845, 133845.76919034,
       142340.12817261, 167184.04085762, 207314.36597542, 187310.78679114,
       223518.55109399, 122275.90962734, 216559.42555316, 138559.33458778,
        22749.59050717, 141190.51269079,  90907.40377171, 373833.87874221,
       244720.49807765, 188853.81273071, 126244.62871315, 231492.62175333,
       137791.0812759 , 175392.32980864, 172394.94245494, 214291.7348904 ,
       323466.48730998,  62048.74819903, 136059.56544727, 394072.50796864,
       169455.47256596, 220089.58507318, 167495.73091408, 169975.62866778,
       157085.2356878 , 122471.5808103 ,  99019.38468002, 181594.21296258,
       326975.25272287, 166135.96023986, 126884.35850377, 135600.32073066,
       202344.59331702, 610525.30894559, 201400.29191341,  85002.78219331,
       124298.52954749,  53725.54537264, 199309.73222549, 185241.14575506,
        -5443.05072147, 231847.93183494, 209662.49237803, 243304.4168567 ,
        92628.40283715, 316600.48628216, 396223.53328398, 361749.24253178,
       249647.12536171, 168306.52313041, 310192.51123051, 204929.10065707,
       174398.27489177, 103383.40479202, 247915.56502998, 148835.39509106,
       141359.42426893,  94360.21474978, 225279.77739521, 118467.83803476,
       231472.09521957, 269616.41458926, 237239.22883729, 175272.95589732,
       121240.52830969, 115850.34150785, 122046.28691318, 137248.21546847,
        97588.45577512, 486008.53440599, 143428.89249529, 221055.54913443,
       160419.88781085, 277997.21882664, 122833.86778499, 177557.82745213,
       187969.43340678, 118571.71378792, 361427.65565886, 253693.46063447,
       143184.58258709, 171442.67828556, 317213.98314973, 210287.90639037,
       200246.31870017, 244950.05275297, 153071.94416426, 206732.32589966,
       105333.2609612 , 117330.06042849, 205247.30090436, 224809.07815731,
       169896.60680658, 110665.71948544, 238421.3674545 , 405823.06128827,
       153280.35990917, 246423.85001041, 134706.9812399 , 178737.04298865,
       253110.93690524,  34497.87859064, 197410.88803598, 154060.6490552 ,
       234044.72064495,  93485.75363608, 290546.68622821, 148945.78539429,
       158318.31665492, 213766.03103   , 439658.9319983 , 229592.99489609,
       283870.6764172 , 277221.08939163,  93619.77401366, 118102.93763322,
       305803.99838562, 457128.26214061, 127861.30458179, 456464.38263057,
       157384.7041776 ,  93305.56544514, 106907.75113656, 127698.57196104,
       293563.28017307, 181339.33773203, 163097.47487877, 111533.39450305,
       125616.47616153, 233900.05393512,  69573.80045428, 274039.59809706,
       200314.79598867, 160517.95326036, 153969.85949751, 355432.12750146,
        76366.63837229, 302090.92023621, 105109.3414724 ,  90022.756202  ,
       140367.69302413, 156014.64796383, 196229.73313897, 114372.83777669,
       172480.79147625, 188436.70240441, 150135.3548563 , 222372.07854221,
       173454.97642446, 398978.05641151, 126849.41102071, 161405.92036872,
       155598.68607894,  65574.15645161, 142874.64222406, 308569.16531119,
       229448.58249171, 272589.60695159, 250851.19167347, -57819.05707998,
       375255.3891409 , 193358.1368032 , 140565.0392142 , 334456.38060089,
       115381.99375536, 328316.9310084 , 309840.39229598, 192751.61206483,
        73790.4623867 ,  93880.90499497, 220193.8284819 , 271892.78981258,
       141912.96115234, 214216.00809804, 183463.18906092, 185355.79863837,
       135691.3784102 , 202839.55879113, 158881.77111522, 245673.78371192,
       182359.58156195, 336838.11565615, 148448.9953865 , 219268.99793501,
       192721.54866166, 184338.9830197 , 218484.78945567, 124568.72679871,
       253888.36504892, 248570.05537362, 254942.65859833, 289079.1360834 ,
       159615.55139782, 330700.1245032 , 127012.96584711,  77666.8174564 ,
       173110.75706538, 125706.29228307, 233608.1891484 ,  74023.31832639,
       134034.19928554, 155152.33458516, 193606.4933348 ,  83407.44524901,
       100294.25255222, 221374.42200482, 256298.14969683, 130823.80508627,
       254653.97378464, 152660.47891743, 144730.62896354, 424286.91111079,
       121079.14159728, 141669.61125758, 183295.17593075,  89280.81038158,
       135703.09647404, 135188.15386233, 325227.24604448, 114222.21423644,
       125387.6333537 , 170795.30966903, 229741.07476431, 183836.64809607,
       359355.75490492, 174774.97151611, 221342.58610575, 195113.23951783,
       114017.00475849, 262461.49124871, 228223.60152897, 153907.89640952,
       166570.62682988, 134309.48395866, 117098.85733391, 139416.05114705,
       245372.22950049, 115775.68791063,  87290.38083762, 182806.07958058,
       236292.88269269, 264441.66597698, 155115.65398262,  90624.33948885,
       194474.57628084, 281507.90009927, 123707.96333406, 313417.96910717,
       138959.96166155, 322884.85858455, 127741.67574362, 211159.90198696,
       172648.0460272 , 336769.63359447, 126623.11780775, 194400.0584329 ,
       175225.73315237, 119227.97121076, 213147.89814048, 329774.82676622,
       386720.02790821, 232365.74164062, 333240.72124833, 382274.16167346,
       262729.76853792, 151117.73545954, 149640.56848133, 145882.84106974,
       340985.11528899, 216095.7760448 , 143153.63127779, 360381.36480461,
       157130.68247878, 154841.93180355, 227598.60552627, 210272.648593  ,
       159193.10553141, 257407.15376822, 287167.78880187, 122778.58225263,
        26808.17234343, 118170.16212075, 251264.53147927, 136003.66658693,
       138092.22800462, 135130.04585308,  80624.50867938, 191507.12482169,
        77192.50674222, 213355.62525928, 204022.76146633, 193099.57454616,
       125464.30909444, 156792.07849178, 216136.38075186, 331614.82045685,
       140167.23588725, 139184.43962032, 231855.28564705,  90428.46627893,
       119688.61498694, 115750.43200616, 146701.5345378 , 117776.05723416,
        96125.62863186, 376830.91146768, 366848.91821985, 118649.66378084,
        81297.12050523, 127284.80066693, 216143.91253339, 116837.11809784,
       137642.9904918 ,  90120.4153766 , 121434.90999406,  71619.83757437,
       113083.24022279, 105024.37339503, 225593.52494982,  91204.7120622 ,
       142025.6591525 , 304617.22815357, 203993.08376767, 359901.89586723,
       117100.03022706, 147811.09884177, 243317.98844312, 412867.01639416,
       130776.58337288, 299767.63308941,  53020.14971347, 190538.55119373,
       260231.83761546, 111051.40679892, 118949.78487411, 183109.94499111,
       179011.13586927, 141530.12551169, 117473.13565543, 250888.03705386,
       147543.03166331, 140460.52137082, 149316.32546585,  94888.75076385,
       155122.19626397, 149416.84162804, 157234.75079159, 219240.38075979,
       140296.85535884, 158874.64721177, 475435.39586684, 200785.56145614,
       114961.22057672, 114503.5272226 , 121353.66222848, 270599.14347279,
       381103.77172395, 145814.77311216, 128735.23227644, 173032.04277221,
       129258.88608701, 189858.53839263, 250389.71762631, 127845.0568275 ,
        96927.83101854, 277550.31252921, 174814.67442689, 359658.46395075,
       179650.75162914, 178401.44619665, 217802.82070582, 221714.86424308,
       150730.57162271, 142264.88778869, 261580.27504271, 186830.02402056,
       121558.42793331, 219689.87409863, 128375.29959024, 269597.4358407 ,
       155392.43336109, 126566.039184  , 147128.56387655, 204543.33363223,
        86923.75434101, 203606.52015355, 369436.28412707, 170131.84438795,
       247161.33319644, 109334.36884409, 124045.96656451,  90199.82965038,
       116573.81127224,  82494.18576041, 425306.35843409, 206064.63163631,
       164188.92047206, 140359.56276804, 107139.80191505, 176972.59505013,
       158080.30843721, 338045.43328338, 180249.12496478, 121968.24129684,
       335102.57953156, 260814.05906851, 131126.29491664, 244362.22767522,
       125993.09008014, 260174.09585772, 291343.66960555, 140155.80184908,
       145525.03580898, 225681.20357164, 109741.0872731 , 141416.27046869,
       213633.81490928, 225466.2603456 ,  69587.39510301, 156566.96423087,
       103787.47097347, 108314.71074513, 149246.8045712 , 224923.93912831,
       150604.77416298, 160059.76048197, 120487.68982865, 141366.0874232 ,
       126560.52370666,  93783.52356437, 111024.37013508, 357286.28643807,
       141716.99036645, 126774.79362149, 192075.75655286, 185000.01599928,
        73229.83892469, 209088.36290475,  98793.25556689, 141817.31147779,
        83772.48158749, 159658.23978342, 304229.23353747, 358524.58890688,
       209906.48603513, 106655.77261589, 144397.22733405, 296010.00919404,
       396398.88168546, 177217.16326066, 134182.01388612, 160605.32149583,
       302669.37339678, 120582.71854777, 167978.79404599, 503166.29675452,
       134208.18400884,  51564.86575887, 124892.94235754, 228625.22969451,
       258278.49458555, 148464.10257951, 160780.71450458, 176612.67726025,
       241250.52188209, 149468.53412798, 225606.55199864, 280514.94305592,
       161202.44401454,  70448.02955187, 328431.69789443, 169881.27619294,
       117014.23923224, 138416.64503282, 181916.9223691 , 154000.70962725,
       140842.49806295, 197686.09435718, 211182.62083418, 309813.61333495,
       400734.46465661, 171007.90688902, 240024.57297724, 196072.20013085,
       129094.86505439, 251895.37671443, 145516.77426592, 336851.24070887,
        95225.74990146, 160290.72838048, 150645.61733425, 433370.3635346 ,
       203566.21200282, 161734.78034765, 155148.68302739, 139806.40682813,
       102088.41682948, 272634.61338992, 168392.47439889, 130605.81794568,
       204946.36849524, 144834.83416134, 240462.64113475, 105418.08323726,
       165096.11405036, 202703.77555815, 286360.35624606, 152983.52857822,
       213114.22325565, 159368.70882361, 106837.17121081,  71117.08788987,
       170476.35879328, 205103.45711958,  74057.14042792, 158414.74435206,
       227184.12396737, 300769.70432351,  32501.45939925, 187587.75248026,
       161632.14645888, 247872.86240281, 142726.6380631 , 135414.05800335,
        47043.30707932, 202869.84183942, 473668.43667309, 190873.81972119,
       127519.24562672, 157784.01598671])

In [ ]:
X_train_predict

array([140939.00203398, 182781.6819509 ,  80844.80381634, ...,
       205917.78717743, 146604.02490521, 134397.04025478])

r squared

In [ ]:
from sklearn.metrics import r2_score
X_trainr2=r2_score(y_test, X_test_predict)
X_testr2=r2_score(y_train, X_train_predict)
print(X_trainr2)
print(X_testr2)

0.8926739490993085
0.9394590014741165

MSE

In [ ]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test, reg_predict))

3.5921768330977195

IMPLEMENT RIDGE

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()
parameters={'alpha':[10,15,20,25,30,35,40]}
ridge_regressor=GridSearchCV(ridge,parameters,scoring='neg_mean_squared_error',cv=5)
ridge_regressor.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [10, 15, 20, 25, 30, 35, 40]},
             scoring='neg_mean_squared_error')

In [ ]:

print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 40}
-862999861.1446676

In [ ]:
ridge_X_test=ridge_regressor.predict(X_test)

In [ ]:
ridge_X_train=ridge_regressor.predict(X_train)

In [ ]:
from sklearn.metrics import r2_score
ridge_trainr2=r2_score(y_test, ridge_X_test)
ridge_testr2=r2_score(y_train, ridge_X_train)
print(ridge_trainr2)
print(ridge_testr2)

0.8955428558463339
0.9390782980832666

IMPLEMENT LESSO

In [ ]:
from sklearn.linear_model import Lasso
lasso=Lasso()
parameters={'alpha':[10,15,20,25,30,35,40]}
lesso_regressor=GridSearchCV(ridge,parameters,scoring='neg_mean_squared_error',cv=5)
lesso_regressor.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [10, 15, 20, 25, 30, 35, 40]},
             scoring='neg_mean_squared_error')

In [ ]:
print(lesso_regressor.best_params_)
print(lesso_regressor.best_score_)

{'alpha': 40}
-862999861.1446676